In [1]:
# This is a test for running the 'poisoned_well' neural network model with boilerplate Python code.

In [2]:
# Import Statements
import numpy as np
import pandas as pd
import streamflow_model as S

In [3]:
# Boiletplate Python code to run model, check basic statistics, and an example weight matrix

# 1) load the released (bugged) model and build standardized inputs + target
# train.csv holds the weather/soil inputs AND the observed streamflow; this helper
# builds the 72-hour windowed, z-scored inputs and the aligned target for you
weights = S.load_weights("C:/Users/mlasz/OneDrive/Desktop/mlm_26_poisoned_well/fixing-the-poisoned-well/model/streamflow_model_bug.npz")
feats = S.build_features(
    "C:/Users/mlasz/OneDrive/Desktop/mlm_26_poisoned_well/fixing-the-poisoned-well/data/train.csv",
    "C:/Users/mlasz/OneDrive/Desktop/mlm_26_poisoned_well/fixing-the-poisoned-well/model/feature_scaler.json"
)
X, truth = feats["X"], feats["truth"]
print(f"{len(X)} usable examples, {X.shape[1]} features each")

# 2) run the model, and grab hidden activations (for your analysis)
pred, acts = S.forward(weights, X, return_hidden=True)
print("layers with activations:", list(acts.keys()))

18685 usable examples, 77 features each
layers with activations: ['fc1', 'fc2', 'fc3', 'fc4', 'fc5', 'fc6']


In [4]:
# 3) basic statistics
print("\nprediction stats (mm/hr):")
print(f"mean {pred.mean():.4f} std {pred.std():.4f}"
      f"min {pred.min():.4f} max {pred.max():.4f}")
print(f"skill vs observed: NSE {S.nse(pred, truth):.3f} RMSE {S.rmse(pred, truth):.4f}")


prediction stats (mm/hr):
mean 0.0265 std 0.0264min 0.0078 max 0.5884
skill vs observed: NSE 0.679 RMSE 0.0169


In [ ]:
# peek at an example weight matrix
print(f"\nfc3.weight: shape {weights['fc2.weight'].shape}")
print(np.round(weights["fc1.weight"][:56, :77], 3)) # change these to see diff values
print((weights["fc5.weight"][7]))
print((weights["fc5.weight"][9]))
print((weights["fc2.weight"][19]))
print((weights["fc2.bias"][20]))


fc3.weight: shape (56, 56)
[[-0.001 -0.002 -0.009 ...  0.085 -0.016  0.007]
 [-0.003  0.001 -0.004 ...  0.001 -0.005 -0.002]
 [ 0.002 -0.005 -0.002 ...  0.087 -0.018  0.009]
 ...
 [ 0.001  0.001  0.005 ... -0.001 -0.013 -0.009]
 [ 0.006  0.004 -0.006 ...  0.087 -0.027  0.   ]
 [ 0.001  0.     0.001 ...  0.    -0.001  0.   ]]
[-3.80446719e-32  5.63261872e-24  6.25463622e-03  9.19640902e-03
  1.58315506e-02  4.75562830e-03  1.00941090e-02 -3.72244322e-05
  6.71309838e-03  1.22526623e-02 -3.27012793e-04 -1.96949581e-15
  9.54639632e-03  6.62504981e-11 -2.31743708e-14  1.02440193e-02
 -5.95225210e-19  3.60820297e-04  3.07662663e-12 -2.79360625e-04
 -3.31915473e-08  8.90176371e-03 -3.07722774e-04  8.51042731e-28
  1.11968433e-02 -3.71499596e-06 -9.56312942e-06  8.53197929e-03
  1.00257481e-02  1.30305896e-02  1.29825519e-02  1.08565185e-02
 -7.98601322e-05 -2.83290254e-04  1.00929542e-02 -9.28345908e-05
  1.14144683e-02  2.14789454e-23  1.29112266e-02  2.07335926e-08
  1.20051336e-02  2.21

In [6]:
print(len(feats['truth']))
print(len(pred))

print(feats['truth'][1])
print(pred[1])

print(sum(feats['truth']))
print(sum(pred))

18685
18685
0.025616251
0.026051795
434.9121
494.9033
